kind: Training
spec:
  name: liuhanzuo-qcomem-deployment-exactness-rlmain-20260812d
  image: "artifactory.devops.xiaohongshu.com/media/redaccel:0.9.1-gpu"
  command: 'CODE_DIR=/mnt/tidal-alsh-hilab/dataset/diandian/user/liuhanzuo/indep-bench/qcomem_gpu MODEL_DIR=/mnt/tidal-alsh-hilab/dataset/diandian/user/liuhanzuo/indep-bench_assets/models/Qwen3.5-35B-A3B-59d61f3 DATA_FILE=/mnt/tidal-alsh-hilab/dataset/diandian/user/liuhanzuo/indep-bench_assets/data/qcomem-longbench-validation/longbench_validation.jsonl RUN_DIR=/mnt/tidal-alsh-hilab/dataset/diandian/user/liuhanzuo/indep-bench_assets/runs/qcomem/deployment-exactness-rlmain-20260812d ENV_DIR=/mnt/tidal-alsh-hilab/dataset/diandian/user/liuhanzuo/indep-bench_assets/envs/vllm-cu129-v1 WORKLOAD=longbench LIMIT_PER_DATASET=4 SOURCE_INDEX_START=6 SOURCE_INDEX_END=35 MAX_INPUT_TOKENS=4096 MAX_NEW_TOKENS=4 WARMUPS=1 REPEATS=1 GATE_ONLY=1 MIXED_POLICY_FILE=/mnt/tidal-alsh-hilab/dataset/diandian/user/liuhanzuo/indep-bench_assets/runs/qcomem/layer-sensitivity-reasoning-20260811b/layer_policy.json bash /mnt/tidal-alsh-hilab/dataset/diandian/user/liuhanzuo/indep-bench/qcomem_gpu/launch_deployment_8gpu.sh'
  jobType: PytorchJob
  workerNum: 1
  priority: 10
  restartNum: 0
  resources:
    queueId: 408
    cloudId: 6
    clusterId: 53
    resourcePackageId: 183
  mountPath:
    - /mnt/tidal-alsh-hilab/dataset/diandian
