from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "aggregate_reviews",
    SKILL_ROOT / "scripts" / "aggregate_reviews.py",
)
assert SPEC and SPEC.loader
AGGREGATE_REVIEWS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(AGGREGATE_REVIEWS)


def review(reviewer_id: str, rating: int = 8) -> dict:
    labels = {
        2: "reject",
        4: "marginally_below",
        6: "marginally_above",
        8: "accept",
        10: "strong_accept",
    }
    return {
        "reviewer_id": reviewer_id,
        "round": 1,
        "snapshot_sha256": "a" * 64,
        "role": "technical_soundness",
        "overall_score": rating,
        "confidence": 4,
        "recommendation": labels[rating],
        "dimension_scores": {
            "soundness": 3,
            "presentation": 3,
            "contribution": 3,
        },
        "dimension_justifications": {
            "soundness": "Central claims are supported.",
            "presentation": "The paper is readable.",
            "contribution": "The contribution is useful.",
        },
        "paper_summary": "Summary.",
        "strongest_verified_contribution": "Contribution.",
        "strengths": ["Auditable evidence."],
        "questions": ["What is the closest baseline?"],
        "issues": [],
        "ethics_flag": False,
        "ethics_concerns": "None identified.",
        "llm_usage_disclosure": "Generated by an isolated AI subagent for internal pre-submission review.",
        "score_ceiling_under_current_evidence": rating,
        "predicted_score_after_required_changes": rating,
        "evidence_that_would_raise_score": [],
        "evidence_that_would_lower_score": [],
    }


class ICLRScoringTest(unittest.TestCase):
    def test_valid_discrete_ratings(self) -> None:
        for rating in (2, 4, 6, 8, 10):
            self.assertEqual(
                AGGREGATE_REVIEWS.validate_review(review(f"r{rating}", rating), Path("review.json")),
                [],
            )

    def test_rejects_non_iclr_rating(self) -> None:
        data = review("bad")
        data["overall_score"] = 7
        self.assertTrue(
            any("[2, 4, 6, 8, 10]" in error for error in AGGREGATE_REVIEWS.validate_review(data, Path("bad.json")))
        )

    def test_rejects_decimal_rating(self) -> None:
        data = review("bad")
        data["overall_score"] = 6.8
        self.assertTrue(AGGREGATE_REVIEWS.validate_review(data, Path("bad.json")))

    def test_rejects_recommendation_mismatch(self) -> None:
        data = review("bad", 8)
        data["recommendation"] = "marginally_above"
        self.assertTrue(
            any("must match" in error for error in AGGREGATE_REVIEWS.validate_review(data, Path("bad.json")))
        )

    def test_rejects_non_iclr_dimension(self) -> None:
        data = review("bad")
        data["dimension_scores"]["soundness"] = 5
        self.assertTrue(
            any("soundness" in error for error in AGGREGATE_REVIEWS.validate_review(data, Path("bad.json")))
        )

    def test_panel_uses_official_fields_without_pseudo_index(self) -> None:
        panel = AGGREGATE_REVIEWS.aggregate(
            [review("r1", 8), review("r2", 8), review("r3", 6), review("r4", 8), review("r5", 10)]
        )
        self.assertEqual(panel["overall"]["median"], 8)
        self.assertEqual(panel["dimension_medians"], {"soundness": 3.0, "presentation": 3.0, "contribution": 3.0})
        self.assertNotIn("quality_index", panel)
        self.assertEqual(panel["rating_scale"], [2, 4, 6, 8, 10])


if __name__ == "__main__":
    unittest.main()
