#!/usr/bin/env python3
"""Derive the paper's Mac motivation table from the five frozen MLX runs.

The H20 table is generated by the existing RR2 artifact pipeline.  This script
only adds a compact, scope-separated Mac control showing why agreement with a
shared implementation is weaker than comparison with a vanilla dense path.
"""

from __future__ import annotations

import hashlib
import json
import statistics
from pathlib import Path


PAPER = Path(__file__).resolve().parents[1]
REPO = PAPER.parent
RUN_ROOT = REPO / "results/formal-20260811-ac.LIgSzd"
OUT_ROOT = PAPER / "evidence/mac_m4_motivation"
TABLE = PAPER / "tables/mac_m4_motivation_table.tex"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def median(values: list[float]) -> float:
    if not values:
        raise ValueError("empty median")
    return float(statistics.median(values))


def main() -> None:
    paths = sorted(RUN_ROOT.glob("frozen-*.json"))
    if len(paths) != 5:
        raise RuntimeError(f"expected five frozen Mac runs, found {len(paths)}")

    dense_seconds: list[float] = []
    split_online_seconds = {16: [], 8: [], 4: []}
    split_kl = {16: [], 8: [], 4: []}
    split_top1 = {16: [], 8: [], 4: []}
    interface_top1: list[float] = []
    corpus_bytes = {16: [], 8: [], 4: []}
    compression = {16: [], 8: [], 4: []}
    source_rows = []

    for path in paths:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if payload.get("status") != "completed" or payload.get("formal_result_eligible") is not True:
            raise RuntimeError(f"ineligible Mac run: {path}")
        if payload.get("runtime") != "q-comem-multidoc-mlx-core":
            raise RuntimeError(f"runtime drift: {path}")
        if payload.get("device", {}).get("device_name") != "Apple M4 Pro":
            raise RuntimeError(f"device drift: {path}")
        if payload.get("model") != "mlx-community/Llama-3.2-3B-Instruct-4bit":
            raise RuntimeError(f"model drift: {path}")

        depth = next(row for row in payload["depth_results"] if row["depth"] == 7)
        query_write = {row["query_id"]: row["query_write_seconds"] for row in depth["queries"]}
        dense_seconds.extend(row["dense_full_seconds"] for row in depth["queries"])
        interface_top1.append(depth["mean_interface_top1_agreement_vs_dense"])

        for row in payload["query_results"]:
            bits = row.get("bits")
            if row.get("depth") == 7 and bits in split_online_seconds:
                split_online_seconds[bits].append(
                    query_write[row["query_id"]] + row["online_dequantize_read_seconds"]
                )
        for row in payload["aggregate_results"]:
            bits = row.get("bits")
            if row.get("depth") == 7 and bits in split_kl:
                split_kl[bits].append(row["mean_kl"])
                split_top1[bits].append(row["mean_top1_agreement_rate"])
                corpus_bytes[bits].append(row["corpus_stored_nbytes"])
                compression[bits].append(row["corpus_compression_ratio"])
        source_rows.append(
            {"file": path.name, "bytes": path.stat().st_size, "sha256": sha256(path)}
        )

    for bits in (16, 8, 4):
        if len(split_online_seconds[bits]) != 30:
            raise RuntimeError(f"online cardinality drift for Q{bits}")
        if set(split_top1[bits]) != {1.0}:
            raise RuntimeError(f"top-1 split agreement drift for Q{bits}")
        if len(set(corpus_bytes[bits])) != 1 or len(set(compression[bits])) != 1:
            raise RuntimeError(f"capacity drift for Q{bits}")

    interface = median(interface_top1)
    rows = [
        {
            "method": "Vanilla dense prompt",
            "corpus_store_mib": None,
            "compression_vs_bf16": None,
            "median_online_ms": 1000.0 * median(dense_seconds),
            "speedup_vs_vanilla": 1.0,
            "top1_vs_bf16_split": None,
            "top1_vs_vanilla_dense": 1.0,
            "mean_kl_vs_bf16_split": None,
        }
    ]
    names = {16: "CoMem BF16 split", 8: "CoMem Q8 split", 4: "CoMem Q4 split"}
    for bits in (16, 8, 4):
        rows.append(
            {
                "method": names[bits],
                "corpus_store_mib": corpus_bytes[bits][0] / (1024.0 * 1024.0),
                "compression_vs_bf16": compression[bits][0],
                "median_online_ms": 1000.0 * median(split_online_seconds[bits]),
                "speedup_vs_vanilla": median(dense_seconds) / median(split_online_seconds[bits]),
                "top1_vs_bf16_split": median(split_top1[bits]),
                "top1_vs_vanilla_dense": interface,
                "mean_kl_vs_bf16_split": median(split_kl[bits]),
            }
        )

    summary = {
        "schema_version": "forkaudit-mac-common-mode-motivation-v1",
        "status": "verified_archival_motivation_only",
        "device": "MacBook Pro / Apple M4 Pro / 24 GB unified memory",
        "runtime": "MLX Core",
        "model": "mlx-community/Llama-3.2-3B-Instruct-4bit",
        "model_revision": "7f0dc925e0d0afb0322d96f9255cfddf2ba5636e",
        "workload": "six-document/six-query teacher-forced demonstration set",
        "split_depth": 7,
        "fresh_processes": 5,
        "queries_per_process": 6,
        "source_files": source_rows,
        "rows": rows,
        "interpretation": (
            "Quantized split variants agree with their BF16 split reference at every "
            "answer-token top-1 position, while the shared split reference itself agrees "
            "with vanilla dense at only 71.89%. This archival Mac control motivates an "
            "independent oracle; it is not pooled with the H20 ForkAudit factorial."
        ),
    }

    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    (OUT_ROOT / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    def pct(value: float | None) -> str:
        return "--" if value is None else f"{100.0 * value:.2f}\\%"

    def num(value: float | None, digits: int = 3) -> str:
        return "--" if value is None else f"{value:.{digits}f}"

    lines = [
        "\\begin{table}[t]",
        "\\caption{Unpooled Mac motivation context (Apple M4 Pro, five fresh MLX processes; median over 30 query executions at split depth 7). Vanilla dense is the external reference. CoMem BF16/Q8/Q4 variants use the same selected documents. Store size is the six-document residual corpus; online time includes query Write, dequantization, and suffix Read. This small teacher-forced demonstration set is not primary ForkAudit evidence and supports no cross-hardware or production-speed claim.}",
        "\\label{tab:mac-motivation}",
        "\\centering\\scriptsize",
        "\\setlength{\\tabcolsep}{2.7pt}",
        "\\begin{tabular}{@{}lrrrr@{}}",
        "\\toprule",
        "Method & Store (MiB) & Online (ms) & Speedup & Top-1 vs. dense \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(
            f"{row['method']} & {num(row['corpus_store_mib'])} & "
            f"{num(row['median_online_ms'], 2)} & {num(row['speedup_vs_vanilla'], 2)}$\\times$ & "
            f"{pct(row['top1_vs_vanilla_dense'])} \\\\" 
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\vspace{0.5mm}",
            "\\parbox{0.98\\linewidth}{\\scriptsize Q8/Q4 retain 100\\% top-1 agreement with the BF16 split path, yet all split rows inherit only 71.89\\% agreement with vanilla dense. The speed column is a small teacher-forced mechanism benchmark, not production RAG throughput.}",
            "\\end{table}",
            "",
        ]
    )
    TABLE.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps(summary, sort_keys=True))


if __name__ == "__main__":
    main()
